name: Restart systemd

on:
  workflow_dispatch:

jobs:
  restartMonoChat:
    runs-on: ubuntu-latest

    steps:
    
      # checkout
      - uses: actions/checkout@v2
    
      # authenticates to Google Cloud
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.gcp_credentials }}'
    
      # restart systemd
      - name: 'restart'
        id: 'compute-ssh'
        uses: 'google-github-actions/ssh-compute@v0'
        with:
          instance_name: 'XXXXXXXXXXX'  # your instance name
          zone: 'XXXXXXXXXXX'  # your zone
          ssh_private_key: '${{ secrets.GCP_SSH_PRIVATE_KEY }}'
          command: 'cd /PATH/TO/MonoChat && sudo bash scripts/systemctl-run.sh restart'
